# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='editor',
            name='article_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'articles/'),
            preserve_default=False,
        ),
    ]
